export const APP_BOOKMARK_DEFAULT = {
  uid: 'bookmarks',
  title: 'Bookmarks',
  shortcuts: [
    {
      id: 'elearn',
      title: 'eLearn',
      logo: 'menu_book',
      color: '#0064B7',
      type: 'url',
      link: 'https://elearn.smu.edu.sg',
    },
    {
      id: 'library',
      title: 'Library',
      logo: 'local_library',
      type: 'url',
      link: 'https://library.smu.edu.sg/',
    },
    {
      id: 'facility_booking',
      title: 'Facility Bookings',
      logo: 'airline_seat_individual_suite',
      color: '#7D7D7D',
      type: 'url',
      link: 'https://fbs.intranet.smu.edu.sg',
    },
    {
      id: 'email',
      title: 'Email',
      logo: 'email',
      color: '#006DCE',
      type: 'url',
      link: 'https://outlook.office.com/owa/?realm=sis.smu.edu.sg',
    },
    {
      id: 'oasis',
      title: 'Oasis',
      logo: 'beach_access',
      color: '#CDA339',
      type: 'url',
      link: 'https://oasis.smu.edu.sg',
    },
    {
      id: 'boss',
      title: 'BOSS',
      logo: 'account_balance',
      color: '#9D916D',
      type: 'url',
      link: 'https://boss.intranet.smu.edu.sg',
    },
  ],
};
