name: Deploy to Production branch
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 0

      - name: Push master to production
        run: git push origin master:production --force
